### ISSUE TITLE
openwrt-ar71xx-通用-mw4530r-v1-squashfs-factory.bin 机场ssr只有1.5M/S

### ISSUE THREAD

**Issue by brainsout** [lsydy1021/MW4530R-LEAN-20210426#1]
谢谢您的固件啊，我是一个小白，尝试过编译，不过搞得很乱，没有成功。
于是我尝试使用前辈你们编译好的固件。发现了一个问题，用这个固件ssr只能跑15M宽带，另一位的也是使用ssr一样只能跑15M的宽带。可是换了另一位的前辈的固件，他使用的是passwall，却能跑满100M的宽带。还有一个信息，机场管理说不支持ssr。可是用您的固件依然能订阅机场的链接。
所以小白的我觉得很奇怪。究竟是甚么原因导致路由器跑机场相同节点速度差别相近10倍？这个链接的固件是跑满100兆的固件：https://www.right.com.cn/forum/thread-2905406-1-1.html
 希望前辈有时间的话，可以解答一下我的疑惑。 (^人^) 拜托啦^^~

**Comment by lsydy1021** [comment]
你要刷入openwrt-ramips-mt7620-xiaomi_miwifi-mini-squashfs-sysupgrade.bin这个文件应该没有问题。






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lsydy1021/MW4530R-LEAN-20210426"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月1日(星期六) 上午10:23
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[lsydy1021/MW4530R-LEAN-20210426] openwrt-ar71xx-通用-mw4530r-v1-squashfs-factory.bin 机场ssr只有1.5M/S (#1)





 
谢谢您的固件啊，我是一个小白，尝试过编译，不过搞得很乱，没有成功。
 于是我尝试使用前辈你们编译好的固件。发现了一个问题，用这个固件ssr只能跑15M宽带，另一位的也是使用ssr一样只能跑15M的宽带。可是换了另一位的前辈的固件，他使用的是passwall，却能跑满100M的宽带。还有一个信息，机场管理说不支持ssr。可是用您的固件依然能订阅机场的链接。
 所以小白的我觉得很奇怪。究竟是甚么原因导致路由器跑机场相同节点速度差别相近10倍？这个链接的固件是跑满100兆的固件：https://www.right.com.cn/forum/thread-2905406-1-1.html
 希望前辈有时间的话，可以解答一下我的疑惑。 (^人^) 拜托啦^^~

**Comment by brainsout** [comment]
您确定吗？因为4530r的cpu是ar9344，小米的是mt7620，挺大不同的。要是您确定没问题，我就刷了，等您回复。------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年5月3日(星期一) 晚上10:09
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [lsydy1021/MW4530R-LEAN-20210426] openwrt-ar71xx-通用-mw4530r-v1-squashfs-factory.bin 机场ssr只有1.5M/S (#1)

**Comment by brainsout** [comment]
好像找到原因了，硬改后需要修改限制。之前的8兆要改成16兆，不过云编译不知道怎么改。
4530r硬件性能很低，不过油管可以满速，下载只能15兆，应该是ss tproxy能油管直连不需要走梯子，其它需要走梯子的话，最高是1.5m/s 因为4530r的性能最多就这样了。
不知道我说的对不对，因为这是猜的。
